approvals:
  # PR needs at least 1 approvals
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^Code:+1$"
  pattern: "^Code:+2$"
  pattern: "^Code:+3$"
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^Code:-1$"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    # OR a collaborator of the repo
    collaborators: true
    # OR one of these guys
    users:
      - piccobit
      - hdstich
commit:
  message:
    # note that there are no default patterns for commit messages
    patterns:
        - "^[A-Z]+-[0-9]+" # starts with uppercase letters, a dash and digits
specification:
    # title requirements AND body AND template requirements have to match
    title:
        # PR title is at least this many characters long
        minimum-length:
            enabled: true
            length: 8
    body:
        # either of these verifications has to be true
        # PR body is at least this many characters long
        minimum-length:
            enabled: true
            length: 8
        # contains a link
        contains-url: false
        # contains an issue number
        contains-issue-number: false
        template:
            # is different from pull request body
            differs-from-body: true
